/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import controlas.Dicionario;
import entidade.Palavra;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;
import util.ConexaoBD;

/**
 *
 * @author art
 */
public class TelaPrincipal
        extends javax.swing.JFrame
{

    private Dicionario dicionario = new Dicionario();

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal()
    {
        initComponents();

        carregaInformacoes();
        
        setTitle( "Dicionário" );
    }
    
    private void carregaInformacoes()
    {
        this.carregaInformacoes( null );
    }

    private void carregaInformacoes( String filtro )
    {
        ArrayList<Palavra> palavras = dicionario.getPalavras( filtro );

        tblPalavras.setModel( new AbstractTableModel()
        {
            @Override
            public String getColumnName( int column )
            {
                switch ( column )
                {
                    case 0:
                        return "Código";
                    case 1:
                        return "Palavra";
                    case 2:
                        return "Significado";
                    default:
                        return "";
                }
            }

            @Override
            public int getColumnCount()
            {
                return 3;
            }

            @Override
            public int getRowCount()
            {
                return palavras.size();
            }

            @Override
            public Object getValueAt( int rowIndex, int columnIndex )
            {
                Palavra p = palavras.get( rowIndex );

                if ( p != null )
                {
                    switch ( columnIndex )
                    {
                        case 0:
                            return p.getCodigo();   
                        case 1:
                            return p.getPalavra();
                        case 2:
                            return p.getSignificado();
                    }

                }

                return "n/d";
            }
        } );
        
        tblPalavras.getColumnModel().getColumn(0).setMinWidth(80);
        tblPalavras.getColumnModel().getColumn(0).setPreferredWidth(80);
        tblPalavras.getColumnModel().getColumn(0).setMaxWidth(80);
    }

    private void limpaCampos()
    {
        txtPalavra.setText( "" );
        txtSignificado.setText( "" );
        txtCode.setText( "" );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings ("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPalavra = new javax.swing.JTextField();
        txtCode = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSignificado = new javax.swing.JTextArea();
        btnSalvar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPalavras = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txtBusca = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Código");

        jLabel2.setText("Palavra");

        txtCode.setEditable(false);

        jLabel3.setText("Significado");

        txtSignificado.setColumns(20);
        txtSignificado.setRows(5);
        jScrollPane1.setViewportView(txtSignificado);

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnSalvarActionPerformed(evt);
            }
        });

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCancelarActionPerformed(evt);
            }
        });

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSair)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalvar))
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(26, 26, 26)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(txtPalavra, javax.swing.GroupLayout.PREFERRED_SIZE, 771, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPalavra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(jButton1)
                    .addComponent(btnSair))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Geral", jPanel1);

        tblPalavras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String []
            {
                "Código", "Palavra", "Significado"
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean []
            {
                false, false, false
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        tblPalavras.setColumnSelectionAllowed(true);
        tblPalavras.getTableHeader().setReorderingAllowed(false);
        tblPalavras.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                tblPalavrasMouseClicked(evt);
            }
        });
        tblPalavras.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                tblPalavrasKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(tblPalavras);
        tblPalavras.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tblPalavras.getColumnModel().getColumnCount() > 0)
        {
            tblPalavras.getColumnModel().getColumn(0).setMinWidth(80);
            tblPalavras.getColumnModel().getColumn(0).setPreferredWidth(80);
            tblPalavras.getColumnModel().getColumn(0).setMaxWidth(80);
        }

        jLabel4.setText("Filtro:");

        txtBusca.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtBuscaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtBusca, javax.swing.GroupLayout.DEFAULT_SIZE, 789, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        jTabbedPane1.addTab("Lista", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtBuscaActionPerformed
    {//GEN-HEADEREND:event_txtBuscaActionPerformed
        carregaInformacoes( txtBusca.getText() );
    }//GEN-LAST:event_txtBuscaActionPerformed

    private void tblPalavrasMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_tblPalavrasMouseClicked
    {//GEN-HEADEREND:event_tblPalavrasMouseClicked
        if ( evt.getClickCount() == 2 )
        {
            int row = tblPalavras.getSelectedRow();

            txtCode.setText( String.valueOf( tblPalavras.getModel().getValueAt( row, 0 ) ) );
            txtPalavra.setText( String.valueOf( tblPalavras.getModel().getValueAt( row, 1 ) ) );
            txtSignificado.setText( String.valueOf( tblPalavras.getModel().getValueAt( row, 2 ) ) );
            jTabbedPane1.setSelectedIndex( 0 );
        }
    }//GEN-LAST:event_tblPalavrasMouseClicked

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnSairActionPerformed
    {//GEN-HEADEREND:event_btnSairActionPerformed
        ConexaoBD.getInstance().shutDown();

        System.exit( 0 );
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCancelarActionPerformed
    {//GEN-HEADEREND:event_btnCancelarActionPerformed
        limpaCampos();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnSalvarActionPerformed
    {//GEN-HEADEREND:event_btnSalvarActionPerformed
        if ( dicionario.validate( txtPalavra.getText(), txtCode.getText() ) )
        {
            Palavra p = new Palavra( txtPalavra.getText(), txtSignificado.getText() );

            if ( txtCode.getText().isBlank() )
            {
                dicionario.addPalavra( p );

                JOptionPane.showMessageDialog( null, "Palavra cadastrada com sucesso!" );
            }

            else
            {
                p.setCodigo( Integer.valueOf( txtCode.getText() ) );

                dicionario.updatePalavra( p );

                JOptionPane.showMessageDialog( null, "Palavra atualizada!" );
            }

            limpaCampos();

            carregaInformacoes( txtBusca.getText() );
        }

        else
        {
            JOptionPane.showMessageDialog( null, "Palavra já cadastrada!" );
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void tblPalavrasKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_tblPalavrasKeyPressed
    {//GEN-HEADEREND:event_tblPalavrasKeyPressed
        if ( tblPalavras.getSelectedRow() != -1 )
        {
            if ( evt.getKeyCode() == KeyEvent.VK_DELETE )
            {
                if ( JOptionPane.YES_OPTION == JOptionPane.showConfirmDialog( null, "Deseja excluir a palavra selecionada?" ) )
                {
                    dicionario.deletePalavra( (Integer)tblPalavras.getValueAt( tblPalavras.getSelectedRow(), 0 ) );
                    
                    carregaInformacoes();
                }
            }
        }
    }//GEN-LAST:event_tblPalavrasKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main( String args[] )
    {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try
        {
            for ( javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels() )
            {
                if ( "Nimbus".equals( info.getName() ) )
                {
                    javax.swing.UIManager.setLookAndFeel( info.getClassName() );
                    break;
                }
            }
        }
        catch ( ClassNotFoundException ex )
        {
            java.util.logging.Logger.getLogger( TelaPrincipal.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        catch ( InstantiationException ex )
        {
            java.util.logging.Logger.getLogger( TelaPrincipal.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        catch ( IllegalAccessException ex )
        {
            java.util.logging.Logger.getLogger( TelaPrincipal.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        catch ( javax.swing.UnsupportedLookAndFeelException ex )
        {
            java.util.logging.Logger.getLogger( TelaPrincipal.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater( new Runnable()
        {
            public void run()
            {
                new TelaPrincipal().setVisible( true );
            }
        } );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblPalavras;
    private javax.swing.JTextField txtBusca;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextField txtPalavra;
    private javax.swing.JTextArea txtSignificado;
    // End of variables declaration//GEN-END:variables
}
